# Generated by Django 5.2 on 2025-04-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='actual_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='target_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='target_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='urgency',
            field=models.IntegerField(default=0),
        ),
    ]
