# Generated by Django 5.2 on 2025-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_actual_value_todo_due_date_todo_importance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='importance',
            field=models.IntegerField(choices=[(0, '低'), (1, '高')], default=0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='urgency',
            field=models.IntegerField(choices=[(0, '低'), (1, '高')], default=0),
        ),
    ]
