# Generated by Django 5.2 on 2025-04-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_importance_alter_todo_urgency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='progress',
        ),
        migrations.AlterField(
            model_name='todo',
            name='actual_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='target_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
