# Generated by Django 5.2 on 2025-04-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_remove_todo_progress_alter_todo_actual_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.IntegerField(choices=[(0, '着手中'), (1, '完了')], default=0),
        ),
    ]
