# Generated by Django 5.2 on 2025-04-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_todo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='status',
        ),
    ]
